# gitgub repository actions 페이지에 나타날 이름
name: CI/CD using github actions & docker

# event trigger
# main 브랜치에 push가 되었을  때 실행
on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      #JDK setting - github actions에서 아용할 JDK 설정(프로젝트나 AWS의 java 버전과 달라도 무방)
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## create application-dev.properties
      - name: make application.properties
        if: contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application-dev.properties
        shell: bash